pinky1_system1:
  ros__parameters:
    waypoints_json: >
      {"A":{"x":0.0,"y":0.0,"yaw":0.0},
       "B":{"x":0.060,"y":0.395,"yaw":0.070},
       "C":{"x":0.45056694884253223,"y":0.42498785253238847,"yaw":1.6022886971368853},
       "D":{"x":0.5491419897425645,"y":-0.4895551603413119,"yaw":-1.6009117175028427},
       "M":{"x":0.2692192294524333,"y":-1.1414312884666327,"yaw":3.0821446616985146}}
    waypoint_edges_json: >
      {"A":["B","D","M"],
       "B":["A","C"],
       "C":["B","D"],
       "D":["A","C","M"],
       "M":["A","D"]}